/* Onboarding ODE model. Time is epochs, amounts are LOGOS.
 * Independent implementation of the model developed in this project.
 * Constant payout until exhaustion, no refill/fees/unlocks, all rewards staked.
 */
(function(root){
 'use strict';
 const defaults={S0:99500000,R0:50000000,P:28.92,N:100,gamma:1,beta:0,K:1,days:7.5,months:6,m:14256,M:1000000,mode:'solve'};
 const epochs=p=>p.months*365/(12*p.days);
 function validate(p){
   const bounds={S0:[1,1e15],R0:[0,1e15],P:[0,1e12],N:[1,1e7],gamma:[0,1],beta:[0,1],K:[1e-9,1e9],days:[.01,365],months:[.01,12],m:[0,1e15],M:[0,1e18]};
   for(const [k,[lo,hi]] of Object.entries(bounds)) if(!Number.isFinite(p[k])||p[k]<lo||p[k]>hi) throw new Error(`${k} must be between ${lo} and ${hi}.`);
   if(!Number.isInteger(p.N))throw new Error('The number of newcomers must be a whole number.');
   if(!['solve','income','total'].includes(p.mode))throw new Error('Choose a valid calculation mode.');
   if(p.mode==='income'&&p.gamma===0&&p.m>0)throw new Error('A positive newcomer income requires a positive newcomer payout share.');
 }
 // Aggregate leadership income generated by mining-funded stake.
 // Small-x integration avoids cancellation; elsewhere expm1/log1p preserve precision.
 function A(t,M,p){
   if(t<=0||M===0||p.P===0)return 0;
   const a=M+p.P,x=a*t/p.S0;
   if(x<.01){
     const n=32;let sum=0;
     for(let j=0;j<=n;j++)sum+=(j===0||j===n?1:j%2?4:2)*(-Math.expm1(-M/a*Math.log1p(x*j/n)));
     return p.P*t*sum/(3*n);
   }
   return Math.max(0,p.P*t-p.S0*Math.expm1(p.P/a*Math.log1p(x)));
 }
 function required(p){
   const T=epochs(p);
   if(p.gamma===0)return {status:'allocation',m:null,M:null,cost:null};
   if(p.beta===0&&p.gamma*p.P*T<=p.N*p.K)return {status:'revenue',m:null,M:null,cost:null};
   let lo=0,hi=p.S0/T;
   const balance=M=>p.gamma*(p.beta*M*T+A(T,M,p))/p.N;
   for(let j=0;balance(hi)<p.K;j++){
     hi*=2;if(j>200||!Number.isFinite(hi))return {status:'numerical',m:null,M:null,cost:null};
   }
   for(let j=0;j<100;j++){const mid=(lo+hi)/2;if(balance(mid)<p.K)lo=mid;else hi=mid;}
   const M=(lo+hi)/2,cost=M*T;
   return {status:cost>p.R0*(1+1e-10)?'budget':'feasible',m:p.gamma*M/p.N,M,cost};
 }
 function state(t,M,p){
   const stop=M>0?p.R0/M:Infinity,u=Math.min(t,stop);
   const m=p.gamma*M/p.N;
   const direct=p.beta*m*u;
   let b=direct+p.gamma*A(u,M,p)/p.N;
   const locked=(1-p.beta)*m*u;
   if(t>u)b+=p.P*(locked+b)/(p.S0+(M+p.P)*u)*(t-u);
   return {t,s:locked+b,b,locked,direct,leadership:b-direct,R:Math.max(0,p.R0-M*u),total:p.S0+M*u+p.P*t};
 }
 function evaluate(p){
   validate(p);
   const target=required(p),T=epochs(p);
   const M=p.mode==='solve'?target.M:p.mode==='total'?p.M:(p.gamma>0?p.N*p.m/p.gamma:0);
   if(M===null)return {target,M:null,T,points:[]};
   const m=p.gamma*M/p.N,stop=M>0?p.R0/M:Infinity,end=state(T,M,p);
   const year=365/p.days;
   let hit=null;
   if(state(year,M,p).b>=p.K*(1-1e-10)){
     let lo=0,hi=year;
     for(let j=0;j<80;j++){const mid=(lo+hi)/2;if(state(mid,M,p).b<p.K)lo=mid;else hi=mid;}
     hit=(lo+hi)/2;
   }
   const points=Array.from({length:181},(_,i)=>state(T*i/180,M,p));
   return {target,M,m,T,stop,end,hit,points,cost:M*T,
     meets:end.b>=p.K*(1-1e-9),epsilon:(M+p.P)*T/p.S0};
 }
 function approximations(p){
   const T=epochs(p);
   const leadershipCoefficient=p.P*T*T/(2*p.S0),denominator=p.beta*T+leadershipCoefficient;
   if(denominator===0||p.gamma===0)return {leading:null,corrected:null};
   const leading=p.K/denominator;
   return {leading,corrected:leading*(1+leadershipCoefficient/denominator*(2*p.N*leading/p.gamma+p.P)*T/(3*p.S0))};
 }
 function checks(){
   const cases=[
     [{...defaults},14255.749404220816],
     [{...defaults,gamma:.75},15376.426069257548],
     [{...defaults,N:1000,months:10},51423.01349568]
   ];
   let count=0;
   for(const [p,expected]of cases){if(Math.abs(required(p).m-expected)>expected*1e-9)throw new Error('Reference rate mismatch');count++;}
   const r=evaluate({...defaults,mode:'income'});
   if(Math.abs(r.end.b-1.000014399853)>1e-8||Math.abs(r.end.R-15310400)>1e-5)throw new Error('Six-month reference mismatch');
   count+=2;return count;
 }
 const api={defaults,epochs,validate,A,required,state,evaluate,approximations,checks};
 if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.Onboarding=api;
})(typeof globalThis==='undefined'?this:globalThis);
